# fly.toml app configuration file generated for rocketseat-fastify on 2026-08-07T22:18:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rocketseat-fastify'
primary_region = 'gru'

[build]

[deploy]
  release_command = "/bin/sh -lc 'DATABASE_URL=\"$DIRECT_DATABASE_URL\" node dist/modules/shared/db/migrate.js'"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "8080"

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
